### ISSUE TITLE
Please clarify the scope of the plugin

### ISSUE THREAD

**Issue by pcav** [thinkWhere/Roadnet#1]
In the About.
Thanks.

**Comment by volcan01010** [comment]
Hi Paulo, Updated in develop branch.  If this is OK, I can repackage the zip file. John

**Comment by pcav** [comment]
Looks good, thanks. Does it apply to your area only, or it's a general tool?

**Comment by volcan01010** [comment]
The tool is very specific to the area e.g. local authorities in Scotland.  They funded part of the development.  However, there are two parts that may be of interest to other QGIS developers.

+ The geometry module contains functions that automatically split features on intersections and update multiple database tables.
    - Try adding an ESU that splits another, or a polygon that overlaps.
    - You should see a warning message
    - Save your changes
    - The geometry of the features should get updated
+  The bin/deploy.py contains code for zipping up the files and copying them to a folder on Amazon S3, along with a plugins.xml file.  We used this to create repos for each version of the code, which was a big help with testing.  (Shippable continuous integration system stores the Amazon credentials as encrypted environment variables).

I will send an explanation to the QGIS developers list once the plugin is published to explain, in case anyone finds those features useful.

**Comment by pcav** [comment]
Please update the About on the site, and I'll publish it.
Thanks a lot.

**Comment by volcan01010** [comment]
Have uploaded corrected version to OSGeo (16_master_679810db).

**Comment by volcan01010** [comment]
Have updated version on OSGeo (20_master_5ed670f8).  This has a demo database so that new users see how it works and what it does.  The user/password are given in the README.md.  I was not able to approve it.
